services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: datapagluavi/drupal:assignment_solve
    ports:
      - 8080:80
    depends_on:
      - postgres
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  
  postgres:
    image: postgres:14
    volumes:
      - drupal-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nopassword

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: